import { parseRemediationArgs, parseSourceWindows, parseTopicAllowlist, runRemediation } from "./topic-grounding-remediation";
describe("topic remediation allowlist",()=>{
 it("requires a non-empty explicit allowlist",()=>{expect(()=>parseTopicAllowlist(["x"])).toThrow();expect(()=>parseTopicAllowlist(["--topicIds="])).toThrow();});
 it("deduplicates deterministically",()=>expect(parseTopicAllowlist(["--topicIds=a,b,a"])).toEqual(["a","b"]));
 it("has no all-blocked mode and defaults to dry-run",()=>{expect(()=>parseRemediationArgs(["--all-blocked","--topicIds=a"])).toThrow();expect(parseRemediationArgs(["--topicIds=a"]).apply).toBe(false);});
 it("requires an explicit unique Topic allowlist and one window per Topic in extraction-only mode",()=>{
  const parsed=parseRemediationArgs(["--sourceExtractionOnly","--topicIds=a","--sourceWindows=a:3-5"]);expect(parsed.sourceExtractionOnly).toBe(true);expect(parsed.apply).toBe(false);
   expect(()=>parseRemediationArgs(["--sourceExtractionOnly"])).toThrow();
  expect(()=>parseRemediationArgs(["--sourceExtractionOnly","--topicIds","--topicIds=a","--sourceWindows=a:1-2"])).toThrow(/topicIds/i);
  expect(()=>parseRemediationArgs(["--sourceExtractionOnly","--topicIds=a","--sourceWindows","--sourceWindows=a:1-2"])).toThrow(/sourceWindows/i);
   expect(()=>parseRemediationArgs(["--sourceExtractionOnly","--topicIds=a,a","--sourceWindows=a:1-2"])).toThrow(/duplicate/i);
   expect(()=>parseRemediationArgs(["--sourceExtractionOnly","--topicIds=a,b","--sourceWindows=a:1-2"])).toThrow(/window/i);
   expect(()=>parseRemediationArgs(["--sourceExtractionOnly","--topicIds=a","--sourceWindows=a:1-2,b:3-4"])).toThrow(/not allowlisted/i);
  expect(()=>parseRemediationArgs(["--sourceExtractionOnly","--all-blocked","--topicIds=a","--sourceWindows=a:1-2"])).toThrow(/all-blocked/i);
 });
 it("validates explicit Topic-bound physical windows",()=>{expect([...parseSourceWindows(["--sourceWindows=a:3-5"],["a"])]).toEqual([["a",{start:3,end:5}]]);expect(()=>parseSourceWindows(["--sourceWindows=b:3-5"],["a"])).toThrow();expect(()=>parseSourceWindows(["--sourceWindows=a:0-5"],["a"])).toThrow();expect(()=>parseSourceWindows(["--sourceWindows=a:5-3"],["a"])).toThrow();expect(()=>parseSourceWindows(["--sourceWindows=a:3-5,a:3-5"],["a"])).toThrow();expect(()=>parseSourceWindows(["--sourceWindows=bad"],["a"])).toThrow();});
});

describe("topic remediation orchestration",()=>{
 const topic=(overrides:any={})=>({id:"t1",nameEn:"Topic",groundingAssignment:null,topicSourceEvidence:[],unit:{id:"u1",nameEn:"Unit",sourcePageStart:1,sourcePageEnd:50,groundingNotesJson:{unitTitle:"U",gradeLevel:"G",subject:"S",learningObjectives:[],concepts:[],facts:[],vocabulary:[],skills:[],topicHints:[],scopeNotes:[]},groundingVersion:1,groundingSourceFingerprint:"fp",topics:[{id:"t1",nameEn:"Topic",order:1},{id:"sibling",nameEn:"Sibling",order:2}],sourceFileOverride:null,subject:{nameEn:"Subject",sourceFile:"book.pdf",grade:{level:5,curriculum:{code:"BRITISH_INTL"}}}},...overrides});
 const blockedTopic=(overrides:any={})=>topic({groundingAssignment:{status:"BLOCKED",method:"AI_MAPPER",unitGroundingVersion:1,unitSourceFingerprint:"fp",assignmentVersion:3,mapperPromptVersion:1,matchedConceptNames:[],matchedHintTitles:null},...overrides});
 function harness(rows:any[]){const assignment={assignGroundingForTopic:jest.fn().mockResolvedValue({outcome:"UNRESOLVED"}),upsert:jest.fn().mockResolvedValue(undefined)},mapper={mapTopic:jest.fn().mockResolvedValue({outcome:"BLOCKED"})},sourceEvidence={getReusable:jest.fn().mockResolvedValue(null),prepareTopicEvidence:jest.fn().mockResolvedValue({status:"NOT_FOUND"})},prisma={client:{topic:{findMany:jest.fn().mockResolvedValue(rows),findUnique:jest.fn(async({where}:any)=>rows.find(r=>r.id===where.id)??null)}}};return{deps:{prisma,assignment,mapper,sourceEvidence,activeModel:jest.fn().mockResolvedValue("model")},assignment,mapper,sourceEvidence,prisma};}
 const extractionOptions=(topicIds:string[],sourceWindows:Map<string,{start:number;end:number}>,apply=false)=>({topicIds,sourceWindows,apply,sourceExtractionOnly:true});
 it("aborts unknown IDs before every side effect",async()=>{const h=harness([topic()]);await expect(runRemediation({topicIds:["t1","missing"],sourceWindows:new Map(),apply:true},h.deps)).rejects.toThrow("Unknown");expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("dry-run reports plans with zero writes/provider/Vision/render service calls",async()=>{const h=harness([topic()]);const r=await runRemediation({topicIds:["t1"],sourceWindows:new Map(),apply:false},h.deps);expect(r.mode).toBe("DRY_RUN");expect(r.topics[0].path).toBe("BLOCKED_NO_AUTHORIZED_SOURCE_WINDOW");expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("dry-run reports actual deterministic, compact, and source-extraction plans",async()=>{
   const deterministic=topic({nameEn:"Roots",unit:{...topic().unit,groundingNotesJson:{...topic().unit.groundingNotesJson,concepts:[{name:"Roots",description:"x",sourcePages:[3],importance:"core"}]}}});
   const compact=topic({nameEn:"Listening Practice",unit:{...topic().unit,groundingNotesJson:{...topic().unit.groundingNotesJson,vocabulary:[{term:"listening",meaning:"x",sourcePages:[4]}]}}});
   const a=harness([deterministic]); expect((await runRemediation({topicIds:["t1"],sourceWindows:new Map(),apply:false},a.deps)).topics[0]).toMatchObject({path:"DETERMINISTIC",deterministicMethod:"KEYWORD_OVERLAP"});
   const b=harness([compact]); expect((await runRemediation({topicIds:["t1"],sourceWindows:new Map(),apply:false},b.deps)).topics[0]).toMatchObject({path:"COMPACT_MAPPER",candidateCount:1,candidateTypes:["vocabulary"]});
   const c=harness([topic()]); expect((await runRemediation({topicIds:["t1"],sourceWindows:new Map([["t1",{start:3,end:5}]]),apply:false},c.deps)).topics[0].path).toBe("SOURCE_EXTRACTION");
   for(const h of [a,b,c]){expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();}
 }); it("reusable READY stops all later work and repeated apply is idempotent",async()=>{const ready=topic({groundingAssignment:{status:"READY",unitGroundingVersion:1,unitSourceFingerprint:"fp"}});const h=harness([ready]);for(let i=0;i<2;i++)expect((await runRemediation({topicIds:["t1"],sourceWindows:new Map(),apply:true},h.deps)).topics[0].path).toBe("REUSE_READY");expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("deterministic recovery stops compact and extraction",async()=>{const h=harness([topic()]);h.assignment.assignGroundingForTopic.mockResolvedValue({outcome:"ASSIGNED",status:"READY"});const r=await runRemediation({topicIds:["t1"],sourceWindows:new Map([["t1",{start:3,end:5}]]),apply:true},h.deps);expect(r.topics[0].path).toBe("DETERMINISTIC");expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("compact recovery stops source extraction",async()=>{const h=harness([topic()]);h.mapper.mapTopic.mockResolvedValue({outcome:"READY"});const r=await runRemediation({topicIds:["t1"],sourceWindows:new Map([["t1",{start:3,end:5}]]),apply:true},h.deps);expect(r.topics[0].path).toBe("COMPACT_MAPPER");expect(h.mapper.mapTopic).toHaveBeenCalledTimes(1);expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("missing window safely blocks extraction",async()=>{const h=harness([topic()]);const r=await runRemediation({topicIds:["t1"],sourceWindows:new Map(),apply:true},h.deps);expect(r.topics[0].path).toBe("BLOCKED_NO_AUTHORIZED_SOURCE_WINDOW");expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("uses TopicSourceEvidenceService only after unresolved compact mapping and reruns assignment after READY",async()=>{const h=harness([topic()]);h.sourceEvidence.prepareTopicEvidence.mockResolvedValue({status:"READY"});h.assignment.assignGroundingForTopic.mockResolvedValueOnce({outcome:"UNRESOLVED"}).mockResolvedValueOnce({outcome:"ASSIGNED",status:"READY"});const r=await runRemediation({topicIds:["t1"],sourceWindows:new Map([["t1",{start:3,end:5}]]),apply:true},h.deps);expect(h.mapper.mapTopic).toHaveBeenCalledTimes(1);expect(h.sourceEvidence.prepareTopicEvidence).toHaveBeenCalledTimes(1);expect(h.assignment.assignGroundingForTopic).toHaveBeenCalledTimes(2);expect(r.readyAfter).toBe(1);});
 it.each(["NOT_FOUND","FAILED"])("keeps %s source evidence safely unresolved",async status=>{const h=harness([topic()]);h.sourceEvidence.prepareTopicEvidence.mockResolvedValue({status});const r=await runRemediation({topicIds:["t1"],sourceWindows:new Map([["t1",{start:3,end:5}]]),apply:true},h.deps);expect(r.finalBlocked).toBe(1);expect(h.assignment.assignGroundingForTopic).toHaveBeenCalledTimes(1);});
 it("reuses exact persisted NOT_FOUND with zero duplicate mapper/Vision/render work",async()=>{const row=topic({topicSourceEvidence:[{status:"NOT_FOUND",topicId:"t1",unitId:"u1",sourceFingerprint:"fp",sourcePageStart:3,sourcePageEnd:5,promptVersion:"topic-source-evidence-v1",extractorModel:"model"}]});const h=harness([row]);const r=await runRemediation({topicIds:["t1"],sourceWindows:new Map([["t1",{start:3,end:5}]]),apply:true},h.deps);expect(r.topics[0].path).toBe("NO_ACTION");expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("preflights every Topic source context before the first side effect",async()=>{const h=harness([topic(),topic({id:"t2",unit:{...topic().unit,subject:{...topic().unit.subject,sourceFile:null}}})]);await expect(runRemediation({topicIds:["t1","t2"],sourceWindows:new Map([["t2",{start:1,end:2}]]),apply:true},h.deps)).rejects.toThrow("No source context");expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();});

 it("extraction-only dry-run validates and plans windows without any side effects",async()=>{const h=harness([blockedTopic()]);const result=await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]])),h.deps);expect(result.mode).toBe("DRY_RUN");expect(result.topics[0]).toMatchObject({path:"SOURCE_EXTRACTION_ONLY",sourceWindow:{start:10,end:12}});expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.assignment.upsert).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.getReusable).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("extraction-only apply invokes evidence extraction once and never the mapper",async()=>{const row=blockedTopic();const h=harness([row]);h.sourceEvidence.prepareTopicEvidence.mockResolvedValue({status:"NOT_FOUND"});const result=await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]]),true),h.deps);expect(result.mode).toBe("APPLY");expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).toHaveBeenCalledTimes(1);expect(h.sourceEvidence.prepareTopicEvidence).toHaveBeenCalledWith(expect.objectContaining({topicId:"t1",unitId:"u1",sourcePageStart:10,sourcePageEnd:12}),expect.objectContaining({sourceKey:"book.pdf"}));});
 it("extraction-only missing window fails before assignment, mapper, or extraction",async()=>{const h=harness([blockedTopic()]);await expect(runRemediation(extractionOptions(["t1"],new Map(),true),h.deps)).rejects.toThrow(/window/i);expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("rejects a window outside the current Unit physical source bounds before side effects",async()=>{const h=harness([blockedTopic()]);await expect(runRemediation(extractionOptions(["t1"],new Map([["t1",{start:49,end:51}]]),true),h.deps)).rejects.toThrow(/outside/i);expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.getReusable).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("extraction-only unknown Topic fails before side effects",async()=>{const h=harness([blockedTopic()]);await expect(runRemediation(extractionOptions(["t1","missing"],new Map([["t1",{start:10,end:12}], ["missing",{start:2,end:3}]]),true),h.deps)).rejects.toThrow("Unknown");expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("mixed valid and invalid extraction windows fail the whole batch before side effects",async()=>{const first=blockedTopic();const second=blockedTopic({id:"t2",unit:{...topic().unit,id:"u2",sourcePageStart:10,sourcePageEnd:20}});const h=harness([first,second]);await expect(runRemediation(extractionOptions(["t1","t2"],new Map([["t1",{start:10,end:12}],["t2",{start:9,end:12}]]),true),h.deps)).rejects.toThrow(/outside|range|window/i);expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();expect(h.assignment.upsert).not.toHaveBeenCalled();expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.getReusable).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();});
 it("reuses exact READY evidence, skips extraction, and reruns assignment",async()=>{const row=blockedTopic({topicSourceEvidence:[{id:"e1",topicId:"t1",unitId:"u1",sourceFingerprint:"fp",sourcePageStart:10,sourcePageEnd:12,promptVersion:"topic-source-evidence-v1",extractorModel:"model",status:"READY",evidenceJson:[{type:"concept",label:"Verified Topic Concept",sourcePages:[10]}]}]});const h=harness([row]);h.sourceEvidence.getReusable.mockResolvedValue(row.topicSourceEvidence[0]);h.assignment.assignGroundingForTopic.mockImplementation(async()=>{row.groundingAssignment={...row.groundingAssignment,status:"READY",method:"KEYWORD_OVERLAP",matchedConceptNames:["Verified Topic Concept"]};return{outcome:"ASSIGNED",method:"KEYWORD_OVERLAP",status:"READY"};});const result=await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]]),true),h.deps);expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();expect(h.assignment.assignGroundingForTopic).toHaveBeenCalledTimes(1);expect(result.topics[0]).toMatchObject({path:"SOURCE_EXTRACTION_ONLY",after:"READY",downstreamSliceVerified:true});});
 it("reuses exact NOT_FOUND evidence without mapper, extraction, or assignment work",async()=>{const row=blockedTopic({topicSourceEvidence:[{id:"e1",topicId:"t1",unitId:"u1",sourceFingerprint:"fp",sourcePageStart:10,sourcePageEnd:12,promptVersion:"topic-source-evidence-v1",extractorModel:"model",status:"NOT_FOUND"}]});const h=harness([row]);h.sourceEvidence.getReusable.mockResolvedValue(row.topicSourceEvidence[0]);const result=await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]]),true),h.deps);expect(result.topics[0]).toMatchObject({path:"NO_ACTION",after:"BLOCKED"});expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).not.toHaveBeenCalled();expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();});
 it("runs assignment preparation after READY extraction and verifies a non-empty slice",async()=>{const row=blockedTopic();row.unit.groundingNotesJson.concepts=[{name:"Extracted Concept",description:"source-backed",sourcePages:[10],importance:"core"}];const h=harness([row]);h.sourceEvidence.prepareTopicEvidence.mockResolvedValue({status:"READY",topicId:"t1",unitId:"u1",sourceFingerprint:"fp",sourcePageStart:10,sourcePageEnd:12,promptVersion:"topic-source-evidence-v1",extractorModel:"model",evidenceJson:[{type:"concept",label:"Extracted Concept",sourcePages:[10]}]});h.assignment.assignGroundingForTopic.mockImplementation(async()=>{row.groundingAssignment={...row.groundingAssignment,status:"READY",method:"KEYWORD_OVERLAP",matchedConceptNames:["Extracted Concept"]};return{outcome:"ASSIGNED",method:"KEYWORD_OVERLAP",status:"READY"};});const result=await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]]),true),h.deps);expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.sourceEvidence.prepareTopicEvidence).toHaveBeenCalledTimes(1);expect(h.assignment.assignGroundingForTopic).toHaveBeenCalledTimes(1);expect(result.topics[0]).toMatchObject({after:"READY",downstreamSliceVerified:true});});
 it("leaves a Topic BLOCKED when extraction returns NOT_FOUND",async()=>{const h=harness([blockedTopic()]);h.sourceEvidence.prepareTopicEvidence.mockResolvedValue({status:"NOT_FOUND"});const result=await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]]),true),h.deps);expect(result.topics[0]).toMatchObject({after:"BLOCKED",path:"SOURCE_EXTRACTION_ONLY"});expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();});
 it("leaves a Topic BLOCKED when extraction returns FAILED",async()=>{const h=harness([blockedTopic()]);h.sourceEvidence.prepareTopicEvidence.mockResolvedValue({status:"FAILED"});const result=await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]]),true),h.deps);expect(result.topics[0]).toMatchObject({after:"BLOCKED",path:"SOURCE_EXTRACTION_ONLY"});expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.assignment.assignGroundingForTopic).not.toHaveBeenCalled();});
 it("does not invoke Topic teaching-step or question generation services",async()=>{const h=harness([blockedTopic()]);h.sourceEvidence.prepareTopicEvidence.mockResolvedValue({status:"NOT_FOUND"});await runRemediation(extractionOptions(["t1"],new Map([["t1",{start:10,end:12}]]),true),h.deps);expect(h.mapper.mapTopic).not.toHaveBeenCalled();expect(h.prisma.client.topic.findMany).toHaveBeenCalledTimes(1);});
});
