import { Injectable } from "@nestjs/common";
import { PrismaService } from "../../prisma/prisma.service";
import { AIProviderFactory } from "../../ai/ai-provider.factory";
import { AIUsageService } from "../../ai/usage/ai-usage.service";
import { CONTENT_AUTHORING_ACTOR_ID } from "../../ai/content-authoring-actor.const";
import { estimateImageTokens, estimateTextTokens, pngDimensions, type ImageDetail } from "../../ai/vision-request-sizing";
export function estimateDataUrlImageTokens(model:string,images:Array<{dataUrl:string}>,detail:ImageDetail):number{return images.reduce((sum,image)=>{const comma=image.dataUrl.indexOf(",");if(!image.dataUrl.startsWith("data:image/png;base64,")||comma<0)throw new Error("Vision image must be a PNG data URL");const {width,height}=pngDimensions(Buffer.from(image.dataUrl.slice(comma+1),"base64"));return sum+estimateImageTokens(model,width,height,detail);},0);}
@Injectable()
export class GroundingVisionExecutionService {
 constructor(private readonly prisma:PrismaService,private readonly providers:AIProviderFactory,private readonly usage:AIUsageService){}
 // Images are priced by the shared tile policy and added to the text estimate, so the reservation is made BEFORE the provider call for the full payload.
 async createAccountingContext(input:{inputText:string;estimatedInputTokens?:number;maxOutputTokens?:number;images?:Array<{dataUrl:string}>;imageDetail?:ImageDetail}){const {providerKey,model}=await this.providers.getActiveProvider();const estimatedInputTokens=input.images?.length?(input.estimatedInputTokens??estimateTextTokens(input.inputText))+estimateDataUrlImageTokens(model,input.images,input.imageDetail??"high"):input.estimatedInputTokens;const estimated=await this.usage.estimateMaxChatCostUsd({providerKey,inputText:input.inputText,estimatedInputTokens,maxOutputTokens:input.maxOutputTokens});const r=await this.usage.reserveBudget(CONTENT_AUTHORING_ACTOR_ID,estimated);if(!r.ok)throw new Error(`Grounding extraction budget reservation refused (${r.reason}).`);return {reservationId:r.reservationId,cost:0,finalized:false};}
 async finalizeFailure(c:any){if(!c.finalized){c.finalized=true;await this.usage.releaseBudget(c.reservationId).catch(()=>undefined);}}
 async finalizeSuccess(c:any){if(!c.finalized){c.finalized=true;await this.usage.reconcileBudget(c.reservationId,c.cost).catch(()=>undefined);}}
 async execute(input:{systemPrompt:string;messages:any[];feature:string;estimatedInputTokens?:number;maxOutputTokens?:number;diagnostics?:Record<string,unknown>;accountingContext?:any}){const {provider,providerKey,model}=await this.providers.getActiveProvider();const c=input.accountingContext??await this.createAccountingContext({inputText:input.systemPrompt,estimatedInputTokens:input.estimatedInputTokens,maxOutputTokens:input.maxOutputTokens});try{const result=await provider.generate({systemPrompt:input.systemPrompt,messages:input.messages,diagnostics:input.diagnostics as any,responseFormat:"json_object",maxOutputTokens:input.maxOutputTokens,transportRetryMode:"none"});const rates=await this.providers.getCostRates(providerKey);const cost=result.inputTokens*rates.costPerInputToken+result.outputTokens*rates.costPerOutputToken;c.cost+=cost;await this.prisma.client.aIUsage.create({data:{userId:CONTENT_AUTHORING_ACTOR_ID,studentId:null,subjectId:null,feature:input.feature,provider:providerKey,model,inputTokens:result.inputTokens,outputTokens:result.outputTokens,creditsUsed:0,costUsd:cost}}).catch(()=>undefined);return {result,model,providerKey,cost,accountingContext:c};}catch(e){if(!input.accountingContext)await this.finalizeFailure(c);throw e;}}
}
