import type { VisualInstruction } from "@smartify/shared-types";

export function TutorVisual({ visual }: { visual: VisualInstruction }) {
  if (visual.kind === "MULTIPLICATION_GROUPS") return <div role="img" aria-label={visual.altText} className="grid gap-2 sm:grid-cols-4" style={{ gridTemplateColumns: `repeat(${Math.min(visual.groups, 4)}, minmax(0, 1fr))` }}>{Array.from({ length: visual.groups }, (_, g) => <div key={g} className="rounded border p-2 text-center">{Array.from({ length: visual.itemsPerGroup }, (_, i) => <span key={i} className="mx-0.5 inline-block">{visual.item === "apple" ? "🍎" : visual.item === "block" ? "■" : "●"}</span>)}</div>)}</div>;
  if (visual.kind === "FRACTION_BAR") return <div role="img" aria-label={visual.altText} className="flex overflow-hidden rounded border">{visual.segments.map((s, i) => <div key={i} className={`h-10 flex-1 border-e ${s === "filled" ? "bg-blue-400" : "bg-white"}`} />)}</div>;
  if (visual.kind === "NUMBER_LINE") return <div role="img" aria-label={visual.altText} className="space-y-2"><div className="flex justify-between border-b-2 border-slate-700">{visual.marks.map((m) => <span key={m} className="relative -bottom-2 bg-white px-1 text-xs">{m}</span>)}</div><p className="text-sm">{visual.jumps?.map((j) => `${j.from} → ${j.to}`).join(" • ")}</p></div>;
  if (visual.kind === "BAR_MODEL") return <div role="img" aria-label={visual.altText} className="space-y-1">{visual.bars.map((b, i) => <div key={i} className="flex items-center gap-2"><span className="w-20 text-xs">{b.label}</span><div className="h-7 rounded bg-blue-300" style={{ width: `${Math.min(100, b.value * 12)}%` }} /><span>{b.value}</span></div>)}</div>;
  return <div role="img" aria-label={visual.altText} className="flex flex-wrap gap-1">{Object.entries({ thousands: visual.thousands ?? 0, hundreds: visual.hundreds ?? 0, tens: visual.tens ?? 0, ones: visual.ones ?? 0 }).flatMap(([k, n]) => Array.from({ length: n }, (_, i) => <span key={`${k}-${i}`} title={k} className="rounded bg-amber-200 px-1 text-xs">{k[0].toUpperCase()}</span>))}</div>;
}
