"use client";

import { useEffect, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { SmartifyButton, SmartifyContainer } from "@smartify/ui";
import { useApiClient } from "@/lib/api-client";
import { getMarketingCopy, type Locale } from "@/content/marketing";

type Child = { id: string; fullName: string; availableSubjects: Array<{ id: string; nameEn: string; nameAr: string; payable: boolean }> };
type Checkout = { referenceId: string; expectedAmountEGP: number; recipientName: string; recipientHandle: string; instructionsEn: string; instructionsAr: string };
type Submission = { id: string; referenceId: string; expectedAmountEGP: number; status: string; createdAt: string };
export default function ParentPaymentsPage() {
  const { locale } = useParams<{ locale: Locale }>(); const isAr = locale === "ar"; const search = useSearchParams(); const { apiFetch } = useApiClient();
  const [children, setChildren] = useState<Child[]>([]); const [childId, setChildId] = useState(search.get("studentId") ?? ""); const [subjectIds, setSubjectIds] = useState<string[]>([]);
  const [submissions, setSubmissions] = useState<Submission[]>([]);
  const [checkout, setCheckout] = useState<Checkout | null>(null); const [amount, setAmount] = useState(""); const [sender, setSender] = useState(""); const [note, setNote] = useState(""); const [file, setFile] = useState<File | null>(null); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const child = children.find(item => item.id === childId);
  useEffect(() => { apiFetch<{ students: Child[] }>("/parent/dashboard/summary").then(data => { setChildren(data.students); const initial = search.get("studentId") ?? data.students[0]?.id ?? ""; setChildId(initial); }).catch(() => setError(isAr ? "تعذر تحميل الأبناء المرتبطين." : "Could not load linked children.")); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => { if (childId) apiFetch<Submission[]>(`/parent/children/${childId}/instapay/submissions`).then(setSubmissions).catch(() => setSubmissions([])); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [childId]);
  async function initiate() { if (!child || subjectIds.length === 0) return; setBusy(true); setError(""); try { const result = await apiFetch<Checkout>(`/parent/children/${child.id}/instapay/subscription/initiate`, { method: "POST", body: JSON.stringify({ subjectIds }) }); setCheckout(result); setAmount(String(result.expectedAmountEGP)); } catch { setError(isAr ? "تعذر بدء الدفع. تحقق من المواد وحاول مجددًا." : "Could not start payment. Check the selected subjects and retry."); } finally { setBusy(false); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!checkout || !file) return; setBusy(true); setError(""); try { const data = new FormData(); data.append("referenceId", checkout.referenceId); data.append("submittedAmountEGP", amount); data.append("senderName", sender); data.append("note", note); data.append("receipt", file); await apiFetch(`/parent/children/${childId}/instapay/receipt`, { method: "POST", body: data }); setStatus(isAr ? "تم رفع الإيصال للمراجعة. سيتم تفعيل الخدمة بعد مراجعة الإدارة." : "Receipt submitted for review. Admin will activate the service after verification."); setSubmissions(await apiFetch<Submission[]>(`/parent/children/${childId}/instapay/submissions`)); } catch { setError(isAr ? "تعذر رفع الإيصال. تأكد من أن الصورة JPEG أو PNG وأقل من 5 ميجابايت." : "Could not submit receipt. Use a JPEG or PNG image under 5 MB."); } finally { setBusy(false); } }
  return <><Navbar locale={locale} copy={getMarketingCopy(locale)}/><main className="py-10"><SmartifyContainer className="max-w-2xl"><Link className="text-sm text-sf-blue-600" href={`/${locale}/parent`}>{isAr ? "العودة للوحة ولي الأمر" : "Back to parent dashboard"}</Link><h1 className="mt-4 text-2xl font-bold text-navy-900">{isAr ? "دفع اشتراك أحد الأبناء" : "Pay for a child’s subscription"}</h1><p className="mt-2 text-sm text-neutral-600">{isAr ? "اختر ابنك والمواد. رفع الإيصال لا يفعّل الخدمة؛ الإدارة تراجع الدفع يدويًا." : "Choose your child and subjects. Uploading a receipt does not activate service; an admin reviews it manually."}</p>
    {!checkout && !status && <div className="mt-6 space-y-4 rounded border bg-white p-5"><label className="block text-sm">{isAr ? "الابن" : "Child"}<select className="mt-1 block w-full rounded border p-2" value={childId} onChange={event => { setChildId(event.target.value); setSubjectIds([]); }}><option value="">{isAr ? "اختر" : "Select"}</option>{children.map(item => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select></label><fieldset><legend className="mb-2 text-sm">{isAr ? "المواد المتاحة للدفع" : "Available subjects"}</legend>{child?.availableSubjects.filter(subject => subject.payable).map(subject => <label key={subject.id} className="me-4 inline-flex items-center gap-2"><input type="checkbox" checked={subjectIds.includes(subject.id)} onChange={event => setSubjectIds(current => event.target.checked ? [...current, subject.id] : current.filter(id => id !== subject.id))}/>{isAr || /arabic|social studies/i.test(subject.nameEn) ? subject.nameAr : subject.nameEn}</label>)}</fieldset><button disabled={busy || !childId || !subjectIds.length} onClick={() => void initiate()} className="rounded bg-navy-900 px-4 py-2 text-white disabled:opacity-50">{isAr ? "إنشاء تعليمات الدفع" : "Create payment instructions"}</button></div>}
    {checkout && !status && <><div className="mt-6 space-y-2 rounded border bg-white p-5 text-sm"><p>{checkout.recipientName} · {checkout.recipientHandle}</p><p>{isAr ? "المبلغ" : "Amount"}: <strong>{checkout.expectedAmountEGP} EGP</strong></p><p>{isAr ? "رقم العملية" : "Reference"}: <strong className="font-mono">{checkout.referenceId}</strong></p><p>{isAr ? checkout.instructionsAr : checkout.instructionsEn}</p></div><form onSubmit={event => void submit(event)} className="mt-4 space-y-3 rounded border bg-white p-5"><label className="block text-sm">{isAr ? "المبلغ المحول" : "Amount transferred"}<input type="number" min="0" step="0.01" className="mt-1 block w-full rounded border p-2" value={amount} onChange={event => setAmount(event.target.value)}/></label><label className="block text-sm">{isAr ? "اسم المرسل" : "Sender name"}<input className="mt-1 block w-full rounded border p-2" value={sender} onChange={event => setSender(event.target.value)}/></label><label className="block text-sm">{isAr ? "ملاحظة" : "Note"}<textarea maxLength={500} className="mt-1 block w-full rounded border p-2" value={note} onChange={event => setNote(event.target.value)}/></label><label className="block text-sm">{isAr ? "صورة الإيصال" : "Receipt image"}<input required type="file" accept="image/jpeg,image/png" onChange={event => setFile(event.target.files?.[0] ?? null)}/></label><SmartifyButton type="submit" variant="ai" disabled={busy || !file}>{isAr ? "إرسال الإيصال للمراجعة" : "Submit receipt for review"}</SmartifyButton></form></>}
    {status && <p role="status" className="mt-6 rounded border border-emerald-200 bg-emerald-50 p-5 text-emerald-800">{status}</p>}{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}
    {submissions.length > 0 && <section className="mt-8"><h2 className="font-semibold">{isAr ? "حالة الإيصالات السابقة" : "Previous receipt status"}</h2><ul className="mt-2 divide-y rounded border bg-white px-4">{submissions.map(item => <li key={item.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>{item.referenceId}</span><span>{isAr ? item.status === "PENDING_VERIFICATION" ? "قيد المراجعة" : item.status === "VERIFIED" ? "تم التفعيل" : "مرفوض" : item.status.replaceAll("_", " ")}</span></li>)}</ul></section>}
  </SmartifyContainer></main></>;
}
