"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { SmartifyContainer } from "@smartify/ui";
import { AdminGuard } from "@/components/AdminGuard";
import { useApiClient } from "@/lib/api-client";
type Ticket = { id: string; title: string; status: string; createdAt: string; student: { email: string; studentProfile?: { fullName: string } }; messages: Array<{ id: string; role: string; content: string; createdAt: string }>; screenshotKey?: string | null; contentDeletedAt?: string | null };
export default function AdminSupportPage() {
  const { locale } = useParams<{ locale: string }>(); const ar = locale === "ar"; const { apiFetch, apiFetchBlob } = useApiClient();
  const [tickets, setTickets] = useState<Ticket[]>([]); const [selected, setSelected] = useState<Ticket | null>(null); const [reply, setReply] = useState(""); const [image, setImage] = useState(""); const [error, setError] = useState("");
  async function load(id?: string) { try { const rows = await apiFetch<Ticket[]>("/admin/support"); setTickets(rows); if (id) setSelected(rows.find(t => t.id === id) ?? await apiFetch<Ticket>(`/admin/support/${id}`)); else if (selected) setSelected(await apiFetch<Ticket>(`/admin/support/${selected.id}`)); } catch { setError(ar ? "تعذر تحميل طلبات الدعم." : "Could not load support tickets."); } }
  useEffect(() => { void load(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => { const timer = window.setInterval(() => void load(selected?.id), 30000); return () => window.clearInterval(timer); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selected?.id]);
  useEffect(() => { let url = ""; if (selected?.screenshotKey && !selected.contentDeletedAt) void apiFetchBlob(`/admin/support/${selected.id}/screenshot`).then(blob => { url = URL.createObjectURL(blob); setImage(url); }).catch(() => setImage("")); else setImage(""); return () => { if (url) URL.revokeObjectURL(url); }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selected?.id, selected?.screenshotKey]);
  async function changeStatus(status: string) { if (!selected) return; await apiFetch(`/admin/support/${selected.id}/status`, { method: "POST", body: JSON.stringify({ status }) }); await load(selected.id); }
  async function sendReply(e: React.FormEvent) { e.preventDefault(); if (!selected || !reply.trim()) return; try { await apiFetch(`/admin/support/${selected.id}/replies`, { method: "POST", body: JSON.stringify({ message: reply }) }); setReply(""); await load(selected.id); } catch { setError(ar ? "تعذر إرسال الرد." : "Could not send reply."); } }
  return <AdminGuard allowedRoles={["SUPPORT", "ADMIN", "SUPER_ADMIN"]}><main className="py-10"><SmartifyContainer><h1 className="text-2xl font-bold">{ar ? "طلبات الدعم الفني" : "Technical support tickets"}</h1>{error && <p role="alert" className="mt-3 text-red-700">{error}</p>}<div className="mt-6 grid gap-5 lg:grid-cols-[minmax(260px,1fr)_2fr]"><section className="space-y-3">{tickets.map(t => <button key={t.id} onClick={() => { setSelected(t); setImage(""); }} className={`w-full rounded-xl border p-4 text-start ${selected?.id === t.id ? "border-blue-500 bg-blue-50" : "bg-white"}`}><strong>{t.student.studentProfile?.fullName ?? t.student.email}</strong><p className="mt-1 line-clamp-2 text-sm">{t.title}</p><span className="mt-2 block text-xs">{t.status} · {new Date(t.createdAt).toLocaleString(ar ? "ar-EG" : "en-US")}</span></button>)}{tickets.length === 0 && <p>{ar ? "لا توجد طلبات مفتوحة." : "No support tickets."}</p>}</section>{selected && <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{selected.student.studentProfile?.fullName ?? selected.student.email}</h2><p className="text-sm text-neutral-500">{selected.status}</p></div><div className="flex gap-2">{["IN_PROGRESS", "CLOSED", "NEW"].map(s => <button key={s} onClick={() => void changeStatus(s)} className="rounded border px-3 py-2 text-xs">{s}</button>)}</div></div>{image && <img src={image} alt={ar ? "صورة المشكلة المرفقة" : "Attached issue screenshot"} className="mt-4 max-h-80 rounded-lg border object-contain"/>}<div className="mt-4 space-y-3">{selected.messages?.filter(m => m.role !== "system").map(m => <article key={m.id} className="rounded-lg bg-neutral-50 p-3"><p className="whitespace-pre-wrap">{m.content}</p><small>{m.role}</small></article>)}</div>{selected.status !== "CLOSED" && <form onSubmit={sendReply} className="mt-4 space-y-2"><textarea value={reply} maxLength={3000} onChange={e => setReply(e.target.value)} className="min-h-24 w-full rounded border p-3" placeholder={ar ? "اكتب ردك للطالب" : "Write a reply to the student"}/><button className="rounded bg-blue-600 px-4 py-2 text-white">{ar ? "إرسال الرد" : "Send reply"}</button></form>}</section>}</div></SmartifyContainer></main></AdminGuard>;
}
