-- NOT APPLIED to any database as part of this task. This migration file was
-- generated by hand (mirroring the existing repo convention of hand-written
-- migration SQL, see 20260927000000_add_topic_grounding_assignment) to match
-- the new `GroundingConceptAlias` Prisma model. A controller session must
-- review and run `prisma migrate deploy` (or equivalent) before this is live.

CREATE TYPE "GroundingConceptAliasKind" AS ENUM ('CONCEPT', 'HINT');

CREATE TABLE "GroundingConceptAlias" (
  "id" TEXT NOT NULL,
  "unitId" TEXT NOT NULL,
  "itemKind" "GroundingConceptAliasKind" NOT NULL,
  "itemName" TEXT NOT NULL,
  "canonicalLabel" TEXT NOT NULL,
  "aliasEn" TEXT,
  "aliasAr" TEXT,
  "generationVersion" INTEGER NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GroundingConceptAlias_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "GroundingConceptAlias_unitId_itemKind_itemName_key" ON "GroundingConceptAlias"("unitId", "itemKind", "itemName");
CREATE INDEX "GroundingConceptAlias_unitId_generationVersion_idx" ON "GroundingConceptAlias"("unitId", "generationVersion");
ALTER TABLE "GroundingConceptAlias" ADD CONSTRAINT "GroundingConceptAlias_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE CASCADE ON UPDATE CASCADE;
